"""LikesModelV4

Revision ID: 249c898d461e
Revises: 041a80b32db7
Create Date: 2024-10-30 20:04:04.528042

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "249c898d461e"
down_revision: Union[str, None] = "041a80b32db7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "likes", "client_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "likes", "liked_client_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "likes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.drop_index("ix_likes_id", table_name="likes")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_likes_id", "likes", ["id"], unique=False)
    op.alter_column(
        "likes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "likes", "liked_client_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "likes", "client_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
