"""ClientsModelV2

Revision ID: 6131cf41dd44
Revises: 6bdcc09809ca
Create Date: 2024-10-29 18:42:41.600439

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6131cf41dd44"
down_revision: Union[str, None] = "6bdcc09809ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clients",
        "gender",
        existing_type=postgresql.ENUM("MALE", "FEMALE", name="gender"),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clients",
        "gender",
        existing_type=sa.String(),
        type_=postgresql.ENUM("MALE", "FEMALE", name="gender"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
